### ISSUE TITLE
Can you publish a release version

### ISSUE THREAD

**Issue by xiaolait** [evansm7/vftool#1]
I very want to try it, but I'm not a apple developer, can you publish a release version?

**Comment by evansm7** [comment]
Hi xiaolait -- I'm building it using Xcode and a free developer account as well.  (I don't even know if a binary I've created will work on someone else's machine, so I'm not making a binary package at this time.)

Have you tried building this in Xcode, signing in with your Apple ID & making a team to sign with?  This article gives some screenshots/pointers:  https://learnappmaking.com/how-to-create-a-free-apple-developer-account/  The Xcode project just needs you to set up an identity to sign with under the "signing & capabilities" tab, and hit build.

HTH!

**Comment by sylvainfilteau** [comment]
FWIW I was able to build and archive the project without supplying my AppleID in Xcode

**Comment by xiaolait** [comment]
I can start a ubuntu server arm64 image, but I can not install it, because the term will pop dialog and I can see clearly
