### ISSUE TITLE
Question: Is there a way to request an IP address?

### ISSUE THREAD

**Issue by pgib** [evansm7/vftool#4]
Just wondering if there's any way to request a particular IP address when starting a VM? Or if not, write a file somewhere containing it so that it can be read in by other things? I'm running PostgreSQL from inside a VM and wanting to connect to it. But I'd rather not have to sign in each time to see what IP address I need to connect to.

**Comment by javacom** [comment]
Setup a fixed IP in your vm will solve the problem.

**Comment by evansm7** [comment]
The host NATs 192.168.64.0/24 to your real network, so choosing a fixed IP on that network works well.  (The default route is .1, so don't use that (or .0, or .255).)
