### ISSUE TITLE
Question: Is it possible to add extra volume to the vm?

### ISSUE THREAD

**Issue by tckb** [evansm7/vftool#5]
Thanks for making the tool and instructions are pretty clear. 

I've had successful launching of vm using the command line. Though, it is possible to connect to the vm, I  see that for my activities it says I do not have enough disk space. my question is: would it be possible to add extra disk.volume to the vm? or just  bumping up the memory sufficient?

**Comment by javacom** [comment]
Please the Closed issue 3
https://github.com/evansm7/vftool/issues/3

**Comment by tckb** [comment]
Thanks @javacom i looked into the blog referred in the issue. That worked!
