### ISSUE TITLE
Question: can change default ubuntu user password?

### ISSUE THREAD

**Issue by cyrus0880** [evansm7/vftool#6]
i want to change default ubuntu user passwd
but try to in ubuntu user enter passwd to change new pw and reboot , not work

i added persistent storage for / & home in -d data.img (50G)

**Comment by javacom** [comment]
If you mount the desktop iso image as vm, passwd would not persistent.

If you just want to use ssh-server for that iso image you should change this and then restart service.
# change /etc/ssh/sshd_config PermitEmptyPasswords to yes

**Comment by cyrus0880** [comment]
if i use server iso is can install to img? not live boot?

**Comment by javacom** [comment]
If you use the Ubuntu server image, please refer to issue #2 , there is a solution.

**Comment by cyrus0880** [comment]
thx is work~
